language: python
python:
- 3.8
- 3.7
- 3.6
- 3.5
install: pip install -U tox-travis
script: tox
deploy:
  provider: pypi
  distributions: sdist bdist_wheel
  user: zaitra
  password:
    secure: Qrpla5rDvlbK336JShuitCr63XbTDcYLvEOqaK19wHZj86t111sLO6FuwQ6whkF+t+S++tx+q3Bs7lGju975LHLdbk8CEZAzL3GyVqDGRtXmsVdpVutuYel4hAcOLGnxKOw0Mb+oPjcYRfMXr9exs5HB3/UjrVtEWJiQMLQ0c1jvLw7ddWUSQAfmmT5sgyKOhnQa8VB8/X9A5XscI/pGARAYEAPZtR/vj8BvNLay2AgmX+0KwTcDxtD1jXaMqVMoQn956nIswRNZqZpOUv8R0jMU4Rp5bnS0IelEwCudD0HjBkjramTMQPzYMpcy+CTPYFdWPKLPA2P+WnMDQCDv7DN/7nzBimHYju3TuTgrd/jc+bayw3Muu+CvyjLX0Fln3tArLihdfxCuToVPq1CIY8RD+GXJ9Yrx5FvmOpaaHBOkkDaAQQ6cZRxyOxoWOxHOCc5fLuOlS1pkpgz2zIisPzED+NZTRR+lT290OKYBdUIcCXVyq6Vuv3SGZ6rxrGqGL4JoNcNVetgol6F2GQ5z7VqJsS7KSaU23EmvlavkYt9mCsEM0LqfQBGYeoonrPGVAHGA9yYZy2XJNnM7wS7eYw9OBo5DbEChOTx8BrSMC+BtYwhenp3XSdpQVt7FDIIS1sDycf58ySI1VXiqq1X92LyiGjPCQ919rmU0AHs+LDw=
  on:
    tags: true
    repo: zaitra/geojson-length
    python: 3.8
